# SPDX-FileCopyrightText: Copyright (c) 2012-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    env:
      PLATFORMS: linux/x86_64
    steps:
      - uses: actions/checkout@v4
      - run: make test
